name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
        arch: [x86, x64]
        exclude:
        - os: ubuntu
          arch: x86
        - os: macos
          arch: x86
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - if: runner.os == 'Linux'
      run: sudo apt-get install -y libreadline-dev
    - uses: actboy168/setup-luamake@master
      with:
        arch: ${{ matrix.arch }}
    - run: luamake -arch ${{ matrix.arch }}
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: lua-debug
        path: publish
  publish:
    runs-on: macos-latest
    needs: compile
    steps:
      - uses: actions/download-artifact@v1.0.0
        with:
          name: lua-debug
          path: publish
      - run: npm install -g vsce
      - name: Publish
        working-directory: publish
        run: |
          chmod -v +x runtime/linux/lua5*/lua
          chmod -v +x runtime/macos/lua5*/lua
          chmod -v +x bin/linux/lua-debug
          chmod -v +x bin/macos/lua-debug
      - run: vsce publish -p ${{ secrets.VSCE_KEY }}
        working-directory: publish
        continue-on-error: true
